image:
  dir: images/
  os_image: 2022-04-04-raspios-bullseye-arm64-lite.img.xz
network:
  dhcpcd: etc/dhcpcd.conf
fs:
  device: /dev/sdc
  mount: /media/vsaraph/
  boot: boot/
  root: rootfs/
  shadow: etc/shadow